In [7]:
import numpy as np

In [8]:
print(np.arange(17,54,7))

[17 24 31 38 45 52]


In [11]:
a=np.random.randint(2,6,2)
a

array([4, 3])

In [13]:
a1=np.random.randint(20,100,16).reshape(4,-1)
a1

array([[28, 69, 83, 91],
       [91, 49, 51, 84],
       [68, 28, 30, 99],
       [82, 77, 70, 28]])

### Pandas 
- It is one of the most important modules of data science
- used to work with data in the form of frames / table
- stands for panel data
- Data Analysis,Manipulation and Cleaning
   - Data Analysis means analysing the data
     - stastics of the data,volume of data etc
   - Data Manipulation means transforming the data from one format to the another
     - Merging,concatinating etc
   - Data cleaning means removing the null data
     - Null data means NaN(Not a Number)
- 2 Data structres in pandas
     - 1).series
        - sequential data
     - 2).Data frame
        - data in tabular form i.e rows and columns
- **installation**
   - pip install pandas
   - import pandas

In [14]:
import pandas as pd

In [15]:
pd.__version__

'0.23.4'

In [16]:
#we can create series using str,tuple,list and dict

In [17]:
# with string
st="xyz abc"
pd.Series(st)

0    xyz abc
dtype: object

In [19]:
# try with input().split()
li=input("type your clg name:").split()
pd.Series(li)


type your clg name:VR Siddhartha Engineering College


0             VR
1     Siddhartha
2    Engineering
3        College
dtype: object

In [20]:
# using tuple/list
t=(6,7,3,4)
pd.Series(t)

0    6
1    7
2    3
3    4
dtype: int64

In [21]:
#using Range()
pd.Series(range(10,30,6))

0    10
1    16
2    22
3    28
dtype: int64

In [24]:
#using Dictionary
dic={'34':"thirty four",12:90,'tuple':(9,8,'hi'),'list':[9,6,4]}
s=pd.Series(dic)
s

34       thirty four
12                90
tuple     (9, 8, hi)
list       [9, 6, 4]
dtype: object

In [25]:
s.index #getting index values

Index(['34', 12, 'tuple', 'list'], dtype='object')

In [27]:
import numpy as np
ar=np.arange(10,40,5)
ass=pd.Series(ar)
ass

0    10
1    15
2    20
3    25
4    30
5    35
dtype: int32

In [28]:
ass[0]

10

In [29]:
ass[0:4]

0    10
1    15
2    20
3    25
dtype: int32

In [30]:
ass.index=[4,5,6,7,9,1]

In [31]:
ass

4    10
5    15
6    20
7    25
9    30
1    35
dtype: int32

In [33]:
li2=[9,3,4,5,6,'hi']
inx=[num for num in range(5,11)]
pd.Series(li2,index=inx)

5      9
6      3
7      4
8      5
9      6
10    hi
dtype: object

In [34]:
#pass the user index to series created using dict
#len(dic)
ix=[num for num in range(10,14)]
pd.Series(dic,index=ix)

10    NaN
11    NaN
12     90
13    NaN
dtype: object

In [35]:
s

34       thirty four
12                90
tuple     (9, 8, hi)
list       [9, 6, 4]
dtype: object

In [36]:
s.index

Index(['34', 12, 'tuple', 'list'], dtype='object')

In [37]:
s['tuple']

(9, 8, 'hi')

In [38]:
s['tuple'][:-1]

(9, 8)

Data Frames
- data is in 2d format

In [39]:
pd.DataFrame(s)

0
34     thirty four
12              90
tuple   (9, 8, hi)
list     [9, 6, 4]

In [41]:
pd.DataFrame(dic)

34  12 tuple  list
0  thirty four  90     9     9
1  thirty four  90     8     6
2  thirty four  90    hi     4

In [42]:
dic

{'34': 'thirty four', 12: 90, 'tuple': (9, 8, 'hi'), 'list': [9, 6, 4]}

In [48]:
data={'int':90,'float':90.67,'str':"ruthu",'prgm':'workshop'}
df2=pd.DataFrame(data,index=[1,2,3,4])
df2

int  float    str      prgm
1   90  90.67  ruthu  workshop
2   90  90.67  ruthu  workshop
3   90  90.67  ruthu  workshop
4   90  90.67  ruthu  workshop

In [50]:
pd.concat([s,df2])

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\api.py:107: RuntimeWarning: '<' not supported between instances of 'int' and 'str', sort order is undefined for incomparable objects
  result = result.union(other)


0   int  float    str      prgm
34     thirty four   NaN    NaN    NaN       NaN
12              90   NaN    NaN    NaN       NaN
tuple   (9, 8, hi)   NaN    NaN    NaN       NaN
list     [9, 6, 4]   NaN    NaN    NaN       NaN
1              NaN  90.0  90.67  ruthu  workshop
2              NaN  90.0  90.67  ruthu  workshop
3              NaN  90.0  90.67  ruthu  workshop
4              NaN  90.0  90.67  ruthu  workshop

In [51]:
df=pd.DataFrame(dic)
print(df)

            34  12 tuple  list
0  thirty four  90     9     9
1  thirty four  90     8     6
2  thirty four  90    hi     4
